### ISSUE TITLE
Django 1.11: unexpected keyword argument 'empty_value'

### ISSUE THREAD

**Issue by clairempr** [dracos/django-date-extensions#16]
Hi,

I've found django-date-extensions really useful with Django 1.10, but after switching to Django 1.11 I get the following error in fields.py:
> File "...\lib\site-packages\django_date_extensions\fields.py", line 164, in __init__
    super(ApproximateDateFormField, self).__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'empty_value'

I use the ApproximateDateField in my model like this:
> date = ApproximateDateField(null=True)

and set up the form in Django Admin like this, setting width and height for some form fields, but nothing special for theApproximateDateFormField:

> def get_form(self, request, obj=None, **kwargs):
       form = super(LetterAdmin, self).get_form(request, obj, **kwargs)
      ...
 return form

I know that `empty_value` is a new attribute of CharField, added in Django 1.11, but I don't know what needs to be done about it. Are there plans to update django-date-extensions to support Django 1.11?

Thanks,
Claire

**Comment by dracos** [comment]
If you don't specify `null=True`, I think it would be okay. I have made https://github.com/dracos/django-date-extensions/pull/17 which should hopefully fix this issue anyway, but note the `null=True` is ignored as (if I've read the code right!) this field currently always stores/retrieves an empty date as the empty string.

**Comment by clairempr** [comment]
I removed the `null=True` and it seems to work fine with Django 1.11 now as is. Thanks!
